### ISSUE TITLE
🐛 ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by cprodhomme** [Sindercube/Packr#1]
Hello,

i use you Github action for [my resource pack](https://github.com/minecraft-fr-net/resource-pack-galith/tree/0c04a472cf69088f8b5965c13693f667376119e9) :

version of the github action : `Sindercube/Packr@v2`

But unfortunately, i have this error on [my build](https://github.com/minecraft-fr-net/resource-pack-galith/actions/runs/6383064827/job/17322962052) : 

```console
Notice:  A new release of pip is available: 23.0.1 -> 23.2.1
Notice:  To update, run: pip install --upgrade pip
Run python -m packr \
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/packr/__main__.py", line 3, in <module>
    from yaml import load, Loader
ModuleNotFoundError: No module named 'yaml'
Error: Process completed with exit code 1.
``` 

Could you check and say if all the config its good ?

Thanks !

**Comment by EvantheGrump** [comment]
There seem to be many issues, but to fix this one, I added PyYAML to pyproject.toml dependencies.
